# [[language]]
# name = "json"
# config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } } 

[[language]]
name = "kitty"
scope = "text.kitty"
roots = []
file-types = ["kitty.conf", { suffix = "kitty/conf" }]
comment-token = "#"
